export const Data = [
  { id: 1, first_name: "Oliy", last_name: "Huikerby", gender: "Female" },
  { id: 2, first_name: "Yvette", last_name: "Geertje", gender: "Female" },
  { id: 3, first_name: "Tam", last_name: "Deedes", gender: "Male" },
  { id: 4, first_name: "Corabelle", last_name: "Shortall", gender: "Female" },
  { id: 5, first_name: "Korrie", last_name: "Marrison", gender: "Genderfluid" },
  { id: 6, first_name: "Hildagard", last_name: "Sacher", gender: "Female" },
  { id: 7, first_name: "Daloris", last_name: "Hails", gender: "Female" },
  { id: 8, first_name: "Collen", last_name: "De La Salle", gender: "Female" },
  { id: 9, first_name: "Felix", last_name: "Lavell", gender: "Male" },
  { id: 10, first_name: "Myrtice", last_name: "Heggman", gender: "Female" },
  { id: 11, first_name: "Sargent", last_name: "Holmyard", gender: "Male" },
  { id: 12, first_name: "Raynard", last_name: "Kift", gender: "Male" },
  { id: 13, first_name: "Jed", last_name: "Yushkin", gender: "Male" },
  { id: 14, first_name: "Jone", last_name: "Counter", gender: "Male" },
  { id: 15, first_name: "Benedetta", last_name: "Nannetti", gender: "Female" },
  { id: 16, first_name: "Millard", last_name: "Durante", gender: "Male" },
  { id: 17, first_name: "Kitti", last_name: "Heyfield", gender: "Female" },
  { id: 18, first_name: "Pamela", last_name: "Ciani", gender: "Female" },
  { id: 19, first_name: "Lambert", last_name: "Kopta", gender: "Male" },
  { id: 20, first_name: "Joell", last_name: "Martinovsky", gender: "Female" },
  { id: 21, first_name: "Cleve", last_name: "Vondrys", gender: "Male" },
  { id: 22, first_name: "Grethel", last_name: "Bompass", gender: "Female" },
  { id: 23, first_name: "Halette", last_name: "Fourmy", gender: "Female" },
  { id: 24, first_name: "Laurene", last_name: "Dailey", gender: "Female" },
  { id: 25, first_name: "Seline", last_name: "Rubinowicz", gender: "Female" },
  { id: 26, first_name: "Tracee", last_name: "Burwin", gender: "Female" },
  { id: 27, first_name: "Mayer", last_name: "Fransewich", gender: "Male" },
  { id: 28, first_name: "Darda", last_name: "Mabbe", gender: "Female" },
  { id: 29, first_name: "Gil", last_name: "McCallister", gender: "Male" },
  { id: 30, first_name: "Prudence", last_name: "Driuzzi", gender: "Female" },
  { id: 31, first_name: "Emmerich", last_name: "Wannan", gender: "Male" },
  { id: 32, first_name: "Guthry", last_name: "Fermor", gender: "Male" },
  { id: 33, first_name: "Curtis", last_name: "O'Fallone", gender: "Male" },
  { id: 34, first_name: "Mariska", last_name: "O'Shevlin", gender: "Female" },
  { id: 35, first_name: "Alberta", last_name: "Iianon", gender: "Female" },
  { id: 36, first_name: "Cord", last_name: "Ancliff", gender: "Male" },
  { id: 37, first_name: "Corabel", last_name: "Maddin", gender: "Female" },
  { id: 38, first_name: "Donnie", last_name: "Derl", gender: "Female" },
  {
    id: 39,
    first_name: "Ashely",
    last_name: "Sandwick",
    gender: "Genderfluid",
  },
  { id: 40, first_name: "Patrick", last_name: "Hobbing", gender: "Male" },
  { id: 41, first_name: "Marigold", last_name: "Ollington", gender: "Female" },
  { id: 42, first_name: "Newton", last_name: "Castane", gender: "Agender" },
  { id: 43, first_name: "Kiri", last_name: "Biggin", gender: "Polygender" },
  { id: 44, first_name: "Moises", last_name: "Leaning", gender: "Male" },
  { id: 45, first_name: "Mikel", last_name: "Gabbotts", gender: "Male" },
  { id: 46, first_name: "Spike", last_name: "Coath", gender: "Male" },
  { id: 47, first_name: "Daniel", last_name: "Ashforth", gender: "Male" },
  { id: 48, first_name: "Rosalie", last_name: "Kneal", gender: "Female" },
  { id: 49, first_name: "Arch", last_name: "Papes", gender: "Male" },
  { id: 50, first_name: "Kinsley", last_name: "Heijne", gender: "Male" },
];

    